version: '3.9'

services:
  app:
    build: .
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    restart: unless-stopped
    stdin_open: true
    tty: true
    depends_on:
      - pg

  pg:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
